// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/task': {
    params: {};
  };
  '/user': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/task' | '/user';
  };
  'routes/home.tsx': {
    id: 'routes/home';
    page: '/';
  };
  'routes/task.tsx': {
    id: 'routes/task';
    page: '/task';
  };
  'routes/user.tsx': {
    id: 'routes/user';
    page: '/user';
  };
};
